v. 0.0.44 More formatting issues...

diff --git a/linux-labs b/linux-labs
--- a/linux-labs
+++ b/linux-labs
@@ -67,7 +67,7 @@ shopt -s nullglob
 
 # ************************* global variable definitions ************************
 g_PROGNAME="$(basename "${0}")"
-g_VERSION="0.0.43"
+g_VERSION="0.0.44"
 g_PROGRAM_NAME="linux-labs"
 g_PROGRAM_DESCRIPTION="A script used to download, setup and grade the CIT-220 lab enviornment"
 g_SCRIPT_URL="https://github.com/DoctorKisow/CIT-220/raw/main/linux-labs"
@@ -163,7 +163,7 @@ function display_usage_message_and_bail_out ()
 function error ()
 {
 	echo
-	echo -e "${g_RED_TEXT}${g_PREFIXSTRING}${g_RESET_ATTS}ERROR:   ${1} - exiting" >&2
+	echo -e "${g_RED_TEXT}${g_PREFIXSTRING}${g_RESET_ATTS}  ERROR: ${1} - exiting" >&2
 	cleanup_and_exit_with_code 1
 }
 
@@ -177,7 +177,7 @@ function help ()
 # (info) - Function for formatted informational messages.
 function info ()
 {
-	echo -e "${g_CYAN_TEXT}${g_PREFIXSTRING}${g_RESET_ATTS}INFO:    ${1}" >&2
+	echo -e "${g_CYAN_TEXT}${g_PREFIXSTRING}${g_RESET_ATTS}   INFO: ${1}" >&2
 }
 
 # (internal_consistency_option_checks) - Function used to validate the some of the more obvious configuration file snafus.
